name: docker_image_artifact_download

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image to download (e.g., langgenius/dify-api:1.0.0)"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: pull image
        run: |
          docker pull langgenius/dify-api:1.0.0

      - name: save image
        run: |
          docker save langgenius/dify-api:1.0.0 > ${{ runner.temp }}/image.tar

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: ${{ runner.temp }}/image.tar
