name: docker_image_artifact_download

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image to download (e.g., langgenius/dify-api:1.0.0)"
        required: true
        default: "langgenius/dify-api:1.0.0"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: pull image
        run: |
          docker pull ${{ inputs.image }}

      - name: generate filename
        id: filename
        run: |
          SAFE_NAME=$(echo "${{ inputs.image }}" | sed 's/[\/:]/_/g')
          echo "SAFE_NAME=${SAFE_NAME}" >> $GITHUB_ENV

      - name: save image
        run: |
          docker save ${{ inputs.image }} > ${{ runner.temp }}/${{ env.SAFE_NAME }}.tar

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SAFE_NAME }}
          path: ${{ runner.temp }}/${{ env.SAFE_NAME }}.tar
