name: docker_image_artifact_download

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: pull image
        run: |
          docker pull langgenius/dify-api:1.0.0

      - name: export image
        run: |
          docker export langgenius/dify-api:1.0.0 > ${{ runner.temp }}/image.tar

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: opencompass
          path: ${{ runner.temp }}/image.tar
