# https://docs.docker.com/build/ci/github-actions/share-image-jobs/
name: docker_image_artifact_download

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Image Artifact Download
        uses: ishworkh/docker-image-artifact-download@v2.1.0
        with:
          image: "langgenius/dify-api"
